write=str(input("Enter text to write to the file: "))
file=open("output.txt","w")
writing_file=file.write(write+"\n")
file.close()
file=open("output.txt","a")
append=str(input("Enter additional text to append: "))
appending_file=file.write(append)
file.close()
file=open("output.txt","r")
reading_file=file.read()
print(reading_file)
file.close()
